### ISSUE TITLE
Conflicts of version with Netty 

### ISSUE THREAD

**Issue by Treydone** [atomix/catalyst#57]
Catalyst has a dependency on Netty 4.0.x but Netty is not backward compatible, so the the 4.1.x and 5.0 are not working due to jar conflicts... Is it possible to bundle the Netty classes inside the Catalyst with a relocation of classes (with maven-shade-plugin for example)? Elasticsearch do this trick in order to avoid conflicts with Lucene and Netty, it might make sense here, what do you think?

Examples:
gRPC/grpc-netty 1.0.1 -> Netty 4.1.3.Final
springframework/spring-web -> 4.1.5.Final

**Comment by dmvk** [comment]
What exact issues are you running into? I'm using catalyst with 4.1.6 and did not notice any problems.

**Comment by Treydone** [comment]
Indeed, I have forced all the Netty deps to 4.1.6.Final and it worked like a charm :) Thx!
